# Generated by Django 5.2.2 on 2025-06-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=20)),
                ("team", models.CharField(max_length=50)),
                ("image_url", models.URLField(blank=True)),
            ],
        ),
    ]
